/** Catálogo Llaveros Impresoreando — 2 productos por página. */
window.IMP_CATALOGO_LLAVEROS = {
  instagram: 'impresoreando',
  instagramUrl: 'https://www.instagram.com/impresoreando/',
  taglinePedido: 'Todo es a pedido',
  titulo: 'Llaveros',
  productos: [
    { n: 1, sku: 'LLDONA001', nombre: 'Llavero Dona', ref: 'refs/01-dona.jpg', seleccionarDiseno: false },
    { n: 2, sku: 'LLESTAR001', nombre: 'Llavero Estrella Mario', ref: 'refs/02-estrella-mario.jpg', seleccionarDiseno: false },
    { n: 3, sku: 'LLMBLOQ001', nombre: 'Llavero Mario Bloques', ref: 'refs/03-mario-bloques.jpg', seleccionarDiseno: true },
    { n: 4, sku: 'LLTAMAG001', nombre: 'Llavero Tamagotchi Gato', ref: 'refs/04-tamagotchi-gato.jpg', seleccionarDiseno: true },
    { n: 5, sku: 'LLCOFFE001', nombre: 'Llavero Coffee', ref: 'refs/05-coffee.jpg', seleccionarDiseno: false },
    { n: 6, sku: 'LLJOYST001', nombre: 'Llavero Joystick', ref: 'refs/06-joystick.jpg', seleccionarDiseno: false },
    { n: 7, sku: 'LLMACCL001', nombre: 'Llavero Mac Classic', ref: 'refs/07-mac-classic.jpg', seleccionarDiseno: true },
    { n: 8, sku: 'LLNICK001', nombre: 'Llavero Nickelodeon', ref: 'refs/08-nickelodeon.jpg', seleccionarDiseno: true },
    { n: 9, sku: 'LLCRASH001', nombre: 'Llavero Crash Bandicoot — Boxes', ref: 'refs/09-crash-boxes.jpg', seleccionarDiseno: false },
    { n: 10, sku: 'LLNARUT001', nombre: 'Llavero Naruto — Akatsuki Cloud', ref: 'refs/10-naruto-cloud.jpg', seleccionarDiseno: false },
    { n: 11, sku: 'LLPOKE001', nombre: 'Llavero Pokémon — Poké Ball', ref: 'refs/11-pokeball.jpg', seleccionarDiseno: false },
    { n: 12, sku: 'LLARCAD001', nombre: 'Llavero Retro Arcade', ref: 'refs/12-retro-arcade.jpg', seleccionarDiseno: true },
    { n: 13, sku: 'LLONEPS001', nombre: 'Llavero One Piece — Sombrero', ref: 'refs/13-onepiece-sombrero.jpg', seleccionarDiseno: false },
    { n: 14, sku: 'LLONEPC001', nombre: 'Llavero One Piece — Calavera', ref: 'refs/14-onepiece-calavera.jpg', seleccionarDiseno: false },
    { n: 15, sku: 'LLONEPC002', nombre: 'Llavero One Piece — Calavera 2', ref: 'refs/15-onepiece-calavera-2.jpg', seleccionarDiseno: false },
    { n: 16, sku: 'LLSUPER001', nombre: 'Llavero Chicas Superpoderosas', ref: 'refs/16-chicas-superpoderosas.jpg', seleccionarDiseno: true },
    { n: 17, sku: 'LLHUELL001', nombre: 'Llavero Huella Porta Foto', ref: 'refs/17-huella-porta-foto.jpg', seleccionarDiseno: true },
    { n: 18, sku: 'LLSUPTE001', nombre: 'Llavero Chicas Superpoderosas — Teléfono', ref: 'refs/18-telefono-superpoderosas.jpg', seleccionarDiseno: false },
    { n: 19, sku: 'LLFRUTI001', nombre: 'Llavero Frutilla — Porta Pastillas', ref: 'refs/19-frutilla-pastillas.jpg', seleccionarDiseno: false },
    { n: 20, sku: 'LLVINIL001', nombre: 'Llavero Vinilos', ref: 'refs/20-vinilos.jpg', seleccionarDiseno: true },
    { n: 21, sku: 'LLCAPSU001', nombre: 'Llavero Cápsula — Porta Pastilla', ref: 'refs/21-capsula-pastilla.jpg', seleccionarDiseno: true },
    { n: 22, sku: 'LLDONAP001', nombre: 'Llavero Dona — Porta Pastilla', ref: 'refs/22-dona-pastilla.jpg', seleccionarDiseno: false },
    { n: 23, sku: 'LLTAMAP001', nombre: 'Llavero Tamagotchi — Porta Pastillas', ref: 'refs/23-tamagotchi-pastillas.jpg', seleccionarDiseno: false },
    { n: 24, sku: 'LLLABIO001', nombre: 'Llavero Labios — Porta Pastillas', ref: 'refs/24-labios-pastillas.jpg', seleccionarDiseno: false },
  ],
};
