/** Catálogo Llaveros Impresoreando — 2 productos por página. */
window.IMP_CATALOGO_LLAVEROS = {
  instagram: 'impresoreando',
  instagramUrl: 'https://www.instagram.com/impresoreando/',
  taglinePedido: 'Todo es a pedido',
  titulo: 'Llaveros',
  productos: [
    { n: 1, sku: 'LLDONA001', nombre: 'Llavero Dona', ref: 'refs/01-dona.jpg', seleccionarDiseno: false },
    { n: 2, sku: 'LLESTAR001', nombre: 'Llavero Estrella Mario', ref: 'refs/02-estrella-mario.jpg', seleccionarDiseno: false },
    { n: 3, sku: 'LLMBLOQ001', nombre: 'Llavero Mario Bloques', ref: 'refs/03-mario-bloques.jpg', seleccionarDiseno: true },
    { n: 4, sku: 'LLBETTY001', nombre: 'Llavero Betty Boop', ref: 'refs/04-betty-boop.jpg', seleccionarDiseno: true },
    { n: 5, sku: 'LLTAMAG001', nombre: 'Llavero Tamagotchi Gato', ref: 'refs/05-tamagotchi-gato.jpg', seleccionarDiseno: true },
    { n: 6, sku: 'LLCOFFE001', nombre: 'Llavero Coffee', ref: 'refs/06-coffee.jpg', seleccionarDiseno: false },
    { n: 7, sku: 'LLJOYST001', nombre: 'Llavero Joystick', ref: 'refs/07-joystick.jpg', seleccionarDiseno: false },
    { n: 8, sku: 'LLSTORM001', nombre: 'Llavero Stormtrooper', ref: 'refs/08-stormtrooper.jpg', seleccionarDiseno: false },
    { n: 9, sku: 'LLMACCL001', nombre: 'Llavero Mac Classic', ref: 'refs/09-mac-classic.jpg', seleccionarDiseno: true },
    { n: 10, sku: 'LLNICK001', nombre: 'Llavero Nickelodeon', ref: 'refs/10-nickelodeon.jpg', seleccionarDiseno: true },
    { n: 11, sku: 'LLCRASH001', nombre: 'Llavero Crash Bandicoot — Boxes', ref: 'refs/11-crash-boxes.jpg', seleccionarDiseno: false },
    { n: 12, sku: 'LLNARUT001', nombre: 'Llavero Naruto — Akatsuki Cloud', ref: 'refs/12-naruto-cloud.jpg', seleccionarDiseno: false },
    { n: 13, sku: 'LLPOKE001', nombre: 'Llavero Pokémon — Poké Ball', ref: 'refs/13-pokeball.jpg', seleccionarDiseno: false },
    { n: 14, sku: 'LLARCAD001', nombre: 'Llavero Retro Arcade', ref: 'refs/14-retro-arcade.jpg', seleccionarDiseno: true },
    { n: 15, sku: 'LLONEPS001', nombre: 'Llavero One Piece — Sombrero', ref: 'refs/15-onepiece-sombrero.jpg', seleccionarDiseno: false },
    { n: 16, sku: 'LLONEPC001', nombre: 'Llavero One Piece — Calavera', ref: 'refs/16-onepiece-calavera.jpg', seleccionarDiseno: false },
    { n: 17, sku: 'LLONEPC002', nombre: 'Llavero One Piece — Calavera 2', ref: 'refs/17-onepiece-calavera-2.jpg', seleccionarDiseno: false },
    { n: 18, sku: 'LLSUPER001', nombre: 'Llavero Chicas Superpoderosas', ref: 'refs/18-chicas-superpoderosas.jpg', seleccionarDiseno: true },
    { n: 19, sku: 'LLHUELL001', nombre: 'Llavero Huella Porta Foto', ref: 'refs/19-huella-porta-foto.jpg', seleccionarDiseno: true },
    { n: 20, sku: 'LLSUPTE001', nombre: 'Llavero Chicas Superpoderosas — Teléfono', ref: 'refs/20-telefono-superpoderosas.jpg', seleccionarDiseno: false },
    { n: 21, sku: 'LLFRUTI001', nombre: 'Llavero Frutilla — Porta Pastillas', ref: 'refs/21-frutilla-pastillas.jpg', seleccionarDiseno: false },
    { n: 22, sku: 'LLVINIL001', nombre: 'Llavero Vinilos', ref: 'refs/22-vinilos.jpg', seleccionarDiseno: true },
    { n: 23, sku: 'LLCAPSU001', nombre: 'Llavero Cápsula — Porta Pastilla', ref: 'refs/23-capsula-pastilla.jpg', seleccionarDiseno: true },
    { n: 24, sku: 'LLDONAP001', nombre: 'Llavero Dona — Porta Pastilla', ref: 'refs/24-dona-pastilla.jpg', seleccionarDiseno: false },
    { n: 25, sku: 'LLTAMAP001', nombre: 'Llavero Tamagotchi — Porta Pastillas', ref: 'refs/25-tamagotchi-pastillas.jpg', seleccionarDiseno: false },
    { n: 26, sku: 'LLLABIO001', nombre: 'Llavero Labios — Porta Pastillas', ref: 'refs/26-labios-pastillas.jpg', seleccionarDiseno: false },
  ],
};
