"""Historias base para el feed de tendencias comida Chile — fechas desde URL de la noticia."""

STORIES = [
    {
        "slug": "chocolate-dubai-suk-ohzom",
        "fecha": "2025-05-23",
        "fuente": "https://ohzom.cl/2025/05/23/de-tiktok-al-supermercado-la-extrana-receta-que-esta-agotando-al-chocolate-dubai-en-tiempo-record/",
        "titulo": "Chocolate Dubai casero (SUK / masa knafe)",
        "formato": "Repostería viral · pistacho y knafe",
        "ingredientes": ["Chocolate para derretir", "Masa filo knafe SUK", "Pasta de pistacho", "Mantequilla"],
        "resumenReceta": "Barra de chocolate rellena con masa knafe crujiente y crema de pistacho; SUK reportó alza de ventas de masa filo tras el viral en TikTok e Instagram.",
        "senal": "muy-alto",
        "vistas": "Millones en TikTok/Reels",
        "engagement": "9.1%",
        "crecimiento": "+340%",
        "hashtags": ["#chocolatedubai", "#knafe", "#recetaviral", "#chilefood", "#suk", "#foodtok", "#pistacho"],
        "plataformas": {
            "tiktok": "Kit y receta replicada en TikTok",
            "instagram": "Reels del armado paso a paso",
            "youtube": "Shorts del corte al relleno",
            "pinterest": "Pins del molde y ingredientes",
        },
    },
    {
        "slug": "chocolate-dubai-sabes",
        "fecha": "2025-04-11",
        "fuente": "https://sabes.cl/2025/04/11/comprar-revisa-conseguir-chile-chocolate-dubai-hizo-viral-tik-tok/",
        "titulo": "Cómo hacer Chocolate Dubai en Chile",
        "formato": "Tutorial · ingredientes de supermercado",
        "ingredientes": ["Pistachos", "Mantequilla", "Fideos de arroz o masa filo", "Chocolate negro", "Molde"],
        "resumenReceta": "Guía chilena para replicar el viral con pistacho, fideos de arroz dorados y chocolate; alternativa comprar en Delart.",
        "senal": "alto",
        "vistas": "Alto share en TikTok",
        "engagement": "8.2%",
        "crecimiento": "+280%",
        "hashtags": ["#chocolatedubai", "#recetachilena", "#pistacho", "#foodtok", "#tutorial", "#postreviral"],
        "plataformas": {
            "tiktok": "Tutorial viral en TikTok",
            "instagram": "Carrusel de ingredientes",
            "youtube": "Shorts paso a paso",
            "pinterest": "Tablero de receta Dubai",
        },
    },
    {
        "slug": "cheesecake-yogur-japones",
        "fecha": "2025-02-03",
        "fuente": "https://www.24horas.cl/tendencias/redes-sociales/la-receta-japonesa-que-se-tomo-las-redes-sociales-rapida-y-sencilla",
        "titulo": "Cheesecake de yogur y galletas (sin horno)",
        "formato": "Postre rápido · 2 ingredientes",
        "ingredientes": ["Yogur griego", "Galletas Oreo o Costa", "Opcional: café o cacao"],
        "resumenReceta": "Yogur y galletas reposadas en frío; versión chilena del viral japonés adaptada en TikTok con galletas locales.",
        "senal": "alto",
        "vistas": "8.2M+",
        "engagement": "7.8%",
        "crecimiento": "+210%",
        "hashtags": ["#cheesecake", "#recetafacil", "#postresinchile", "#foodtok", "#sinhorno", "#yogur"],
        "plataformas": {
            "tiktok": "Viral sin horno en TikTok",
            "instagram": "Reels de montaje en vaso",
            "youtube": "Shorts de textura final",
            "pinterest": "Ideas de vasitos y capas",
        },
    },
    {
        "slug": "golden-cheese-burger",
        "fecha": "2025-05-02",
        "fuente": "https://www.24horas.cl/tendencias/recetas/dia-de-la-hamburguesa-como-hacer-en-casa-la-viralizada-golden-cheese-burger",
        "titulo": "Golden Cheese Burger smash",
        "formato": "Hamburguesa viral · doble queso",
        "ingredientes": ["Huachalomo", "Sobrecostilla", "Longaniza", "Queso cheddar", "Pan brioche", "Cebolla morada"],
        "resumenReceta": "Smash burger con carne molida, longaniza y doble capa de queso fundido; viral por textura crujiente en redes.",
        "senal": "alto",
        "vistas": "Millones en Reels",
        "engagement": "7.2%",
        "crecimiento": "+165%",
        "hashtags": ["#goldenburger", "#smashburger", "#recetaviral", "#foodtok", "#hamburguesa", "#chile"],
        "plataformas": {
            "tiktok": "Smash burger en TikTok",
            "instagram": "Reels del queso fundido",
            "youtube": "Shorts de armado",
            "pinterest": "Pins de burger casera",
        },
    },
    {
        "slug": "arepa-pino-fusion",
        "fecha": "2025-08-22",
        "fuente": "https://www.biobiochile.cl/noticias/sociedad/curiosidades/2025/08/22/fusion-venezolana-chilena-de-cara-al-18-arepas-con-pino-desatan-opiniones-mixtas-en-redes-sociales.shtml",
        "titulo": "Arepa de pino (fusión Fiestas Patrias)",
        "formato": "Fusión · debate en redes",
        "ingredientes": ["Harina de maíz precocida", "Pino chileno", "Cebolla", "Aceitunas", "Huevo duro"],
        "resumenReceta": "Arepa venezolana rellena con pino chileno; viral previo al 18 con opiniones divididas en TikTok e Instagram.",
        "senal": "medio-alto",
        "vistas": "100K+ visualizaciones",
        "engagement": "8.5%",
        "crecimiento": "+190%",
        "hashtags": ["#arepadeepino", "#18septiembre", "#fusion", "#foodtok", "#recetachilena", "#debate"],
        "plataformas": {
            "tiktok": "Video polémico en TikTok",
            "instagram": "Reels de la fusión",
            "youtube": "Shorts del emplatado",
            "pinterest": "Receta fusión guardada",
        },
    },
    {
        "slug": "empanada-chilezolana",
        "fecha": "2025-09-16",
        "fuente": "https://www.24horas.cl/tendencias/redes-sociales/empanada-chilezolana-fusion-gastronomica-debate-redes-sociales",
        "titulo": "Empanada Chilezolana ($2.000)",
        "formato": "Emprendimiento · edición 18",
        "ingredientes": ["Masa de arepa", "Pino chileno", "Aceituna", "Huevo"],
        "resumenReceta": "Masa venezolana con pino chileno lanzada para Fiestas Patrias; más de 100 mil views en Instagram del local Rincón Venezolano.",
        "senal": "medio-alto",
        "vistas": "100K+ en Instagram",
        "engagement": "7.1%",
        "crecimiento": "+140%",
        "hashtags": ["#chilezolana", "#empanada", "#18septiembre", "#fusion", "#foodie", "#reelschile"],
        "plataformas": {
            "tiktok": "Clips del local en TikTok",
            "instagram": "Serie viral en Instagram",
            "youtube": "Shorts de degustación",
            "pinterest": "Ideas fusión 18",
        },
    },
    {
        "slug": "marraqueta-palta-mundial",
        "fecha": "2025-09-03",
        "fuente": "https://reportediario.cl/2025/09/03/marraqueta-y-palta-el-desayuno-campeon-de-chile-en-el-mundial-de-ibai/",
        "titulo": "Marraqueta con palta (Mundial desayunos)",
        "formato": "Patriotero · competencia viral",
        "ingredientes": ["Marraqueta", "Palta", "Sal", "Limón opcional"],
        "resumenReceta": "Desayuno chileno impulsado por el Mundial de Ibai; Boric y redes posicionaron marraqueta con palta vs. desayuno peruano.",
        "senal": "alto",
        "vistas": "Millones en votaciones",
        "engagement": "6.5%",
        "crecimiento": "+220%",
        "hashtags": ["#marraquetaconpalta", "#desayunochileno", "#foodtok", "#chile", "#viral", "#palta"],
        "plataformas": {
            "tiktok": "Votación y memes en TikTok",
            "instagram": "Reels del desayuno",
            "youtube": "Shorts de reacciones",
            "pinterest": "Pins desayuno chileno",
        },
    },
    {
        "slug": "empanada-airfryer",
        "fecha": "2025-09-08",
        "fuente": "https://reportediario.cl/2025/09/08/empanadas-de-pino-crujientes-en-freidora-de-aire-un-clasico-chileno-reinventado/",
        "titulo": "Empanadas de pino en air fryer",
        "formato": "Clásico reinventado · freidora de aire",
        "ingredientes": ["Harina", "Manteca", "Pino", "Huevo duro", "Aceitunas", "Pasas"],
        "resumenReceta": "Empanadas crujientes sin horno convencional; tendencia de cocina chilena adaptada a freidora de aire en redes.",
        "senal": "alto",
        "vistas": "Alto guardado en Reels",
        "engagement": "6.8%",
        "crecimiento": "+130%",
        "hashtags": ["#empanadas", "#airfryer", "#pino", "#recetachilena", "#foodtok", "#18septiembre"],
        "plataformas": {
            "tiktok": "Tutorial air fryer TikTok",
            "instagram": "Reels crujientes",
            "youtube": "Shorts del pincelado",
            "pinterest": "Receta empanada air fryer",
        },
    },
    {
        "slug": "pastel-choclo-merengue",
        "fecha": "2025-09-24",
        "fuente": "https://www.24horas.cl/tendencias/redes-sociales/tiktoker-pastel-choclo-merengue-debate",
        "titulo": "Pastel de choclo con merengue",
        "formato": "Debate regional · receta del sur",
        "ingredientes": ["Choclo", "Carne molida", "Merengue", "Cebolla", "Polvo de hornear"],
        "resumenReceta": "Tiktoker de Osorno viraliza pastel de choclo dulce con merengue; debate sur vs. centro en comentarios.",
        "senal": "medio-alto",
        "vistas": "200K+ en TikTok",
        "engagement": "7.9%",
        "crecimiento": "+155%",
        "hashtags": ["#pasteldechoclo", "#merengue", "#recetachilena", "#foodtok", "#osorno", "#debate"],
        "plataformas": {
            "tiktok": "Viral @gallardo_martin",
            "instagram": "Reels del debate",
            "youtube": "Shorts de reacciones",
            "pinterest": "Variantes pastel choclo",
        },
    },
    {
        "slug": "sopaipleto-osorno",
        "fecha": "2026-04-14",
        "fuente": "https://www.biobiochile.cl/noticias/sociedad/historia/2026/04/14/sopaipleto-la-innovacion-culinaria-que-revoluciona-osorno-lo-hice-para-la-juventud.shtml",
        "titulo": "Sopaipleto de Osorno (30 cm)",
        "formato": "Street food · completo + sopaipilla",
        "ingredientes": ["Sopaipilla", "Vienesa", "Palta", "Tomate", "Mostaza opcional"],
        "resumenReceta": "Fusión completo y sopaipilla del local El Pato en Barrio Lynch; viral por tamaño y precio accesible para estudiantes.",
        "senal": "alto",
        "vistas": "Alto share regional",
        "engagement": "7.0%",
        "crecimiento": "+125%",
        "hashtags": ["#sopaipleto", "#osorno", "#comidachilena", "#streetfood", "#foodtok", "#completo"],
        "plataformas": {
            "tiktok": "Videos del local en TikTok",
            "instagram": "Reels del sopaipleto",
            "youtube": "Shorts de degustación",
            "pinterest": "Pins comida Osorno",
        },
    },
    {
        "slug": "completo-italiano-fit",
        "fecha": "2026-05-22",
        "fuente": "https://reportediario.cl/2026/05/22/completo-italiano-fit-la-receta-viral-de-apenas-342-calorias/",
        "titulo": "Completo italiano fit (342 kcal)",
        "formato": "Receta saludable · macros en pantalla",
        "ingredientes": ["Vienesa de pollo casera", "Pan hot dog", "Quesillo", "Huevo", "Palta", "Tomate"],
        "resumenReceta": "Versión baja en calorías del completo italiano con vienesa de pollo y mayonesa fit sin aceite; viral de Sweet Fran.",
        "senal": "alto",
        "vistas": "420K+",
        "engagement": "6.9%",
        "crecimiento": "+180%",
        "hashtags": ["#completoitaliano", "#recetasfit", "#comidachilena", "#macros", "#sweetfran", "#reels"],
        "plataformas": {
            "tiktok": "Receta fit en TikTok",
            "instagram": "Reels con macros",
            "youtube": "Shorts del armado",
            "pinterest": "Completos saludables",
        },
    },
    {
        "slug": "torta-completo-gabo",
        "fecha": "2026-05-19",
        "fuente": "https://www.tvn.cl/noticias/tendencias/influencer-crea-torta-de-completo-y-desata-polemica-en-redes-sociales",
        "titulo": "Torta de completo (Gabo Gutiérrez)",
        "formato": "Challenge viral · comida típica",
        "ingredientes": ["Pan de molde", "Vienesas", "Palta", "Tomate", "Mayonesa", "Queso"],
        "resumenReceta": "Capas de pan, vienesa, palta y tomate en forma de torta; viral previo a la torta de arroz del mismo influencer.",
        "senal": "muy-alto",
        "vistas": "Viral en TikTok e IG",
        "engagement": "9.8%",
        "crecimiento": "+250%",
        "hashtags": ["#tortadecompleto", "#completo", "#gabogutierrez", "#foodtok", "#viral", "#chile"],
        "plataformas": {
            "tiktok": "Viral inicial en TikTok",
            "instagram": "Reels de la torta",
            "youtube": "Shorts del armado",
            "pinterest": "Ideas torta salada",
        },
    },
    {
        "slug": "duelo-sanguches-barrientos",
        "fecha": "2026-06-03",
        "fuente": "https://reportediario.cl/2026/06/03/alvaro-barrientos-responde-a-chef-peruano-por-viral-duelo-de-sanguches/",
        "titulo": "Duelo de sánguches: completo vs. lomo",
        "formato": "Debate viral · gastronomía",
        "ingredientes": ["Pan frica", "Vienesa", "Palta", "Tomate", "Mayonesa", "Carne de lomo"],
        "resumenReceta": "Chef peruano enfrentó completo italiano con lomo saltado en Instagram; Álvaro Barrientos respondió invitando a cocinar sabores chilenos.",
        "senal": "medio-alto",
        "vistas": "Debate masivo en IG",
        "engagement": "7.4%",
        "crecimiento": "+145%",
        "hashtags": ["#completoitaliano", "#sanguche", "#foodtok", "#chile", "#viral", "#barrientos"],
        "plataformas": {
            "tiktok": "Reacciones en TikTok",
            "instagram": "Duelo en Instagram",
            "youtube": "Shorts del completo",
            "pinterest": "Sánguches chilenos",
        },
    },
    {
        "slug": "torta-arroz-huevo",
        "fecha": "2026-06-03",
        "fuente": "https://www.biobiochile.cl/noticias/sociedad/viral/2026/06/03/de-la-torta-de-completo-a-la-de-arroz-con-huevo-y-tomate-influencer-la-rompe-con-preparacion.shtml",
        "titulo": "Torta de arroz con huevo y tomate",
        "formato": "Challenge Gabo Gutiérrez",
        "ingredientes": ["Arroz apelmazado", "Mayonesa", "Vienesas", "Tomate", "Huevos", "Papel aluminio"],
        "resumenReceta": "Capas de arroz, mayonesa, tomate y vienesa terminadas con huevos fritos; viral tras la torta de completos del mismo influencer.",
        "senal": "muy-alto",
        "vistas": "157K+ likes TikTok",
        "engagement": "10.2%",
        "crecimiento": "+200%",
        "hashtags": ["#tortadearroz", "#recetachilena", "#gabogutierrez", "#foodtok", "#viral", "#huevofrito"],
        "plataformas": {
            "tiktok": "Viral Gabo Gutiérrez",
            "instagram": "Reels paralelos",
            "youtube": "Shorts del corte",
            "pinterest": "Ideas torta salada",
        },
    },
    {
        "slug": "queque-vainilla-barrientos",
        "fecha": "2026-06-09",
        "fuente": "https://www.encancha.cl/enlahora/bienestar/2026/06/09/receta-de-queque-casero-de-vainilla-al-estilo-del-chef-alvaro-barrientos-facil-muy-rapido-y-economico/",
        "titulo": "Queque casero de vainilla (chef Barrientos)",
        "formato": "Repostería económica · horno",
        "ingredientes": ["Harina", "Azúcar", "Huevos", "Aceite", "Leche", "Vainilla", "Polvos de hornear"],
        "resumenReceta": "Bizcocho húmedo con medición en gramos; clip del chef replicado en TikTok e Instagram por lo simple y económico.",
        "senal": "medio-alto",
        "vistas": "Alto share en Reels",
        "engagement": "6.4%",
        "crecimiento": "+110%",
        "hashtags": ["#queque", "#recetafacil", "#vainilla", "#foodtok", "#reposteria", "#chile"],
        "plataformas": {
            "tiktok": "Receta en TikTok",
            "instagram": "Reels del horneado",
            "youtube": "Shorts del corte",
            "pinterest": "Pins queque casero",
        },
    },
    {
        "slug": "pan-amasado-barrientos",
        "fecha": "2026-06-13",
        "fuente": "https://www.encancha.cl/enlahora/bienestar/2026/06/13/receta-facil-de-pan-amasado-por-el-chef-alvaro-barrientos-rapido-y-para-el-mejor-desayuno/",
        "titulo": "Pan amasado rápido (chef Barrientos)",
        "formato": "Pan chileno · horno",
        "ingredientes": ["Harina", "Mantequilla", "Levadura", "Sal", "Azúcar", "Agua"],
        "resumenReceta": "Pan amasado dorado por fuera y blando por dentro; receta del chef viralizada en redes de cocina chilena.",
        "senal": "alto",
        "vistas": "Alto engagement invierno",
        "engagement": "7.1%",
        "crecimiento": "+135%",
        "hashtags": ["#panamasado", "#recetachilena", "#desayuno", "#foodtok", "#hornear", "#chile"],
        "plataformas": {
            "tiktok": "Amasado en TikTok",
            "instagram": "Reels del horno",
            "youtube": "Shorts del pan caliente",
            "pinterest": "Receta pan amasado",
        },
    },
    {
        "slug": "ceviche-camarones-cochayuyo",
        "fecha": "2026-06-16",
        "fuente": "https://www.biobiochile.cl/biobiotv/programas/yo-invito/2026/06/16/yo-invito-un-entretenido-ceviche-de-camarones-y-cochayuyo.shtml",
        "titulo": "Ceviche de camarones y cochayuyo",
        "formato": "Mariscos · ingrediente nacional",
        "ingredientes": ["Camarones", "Cochayuyo", "Limón", "Cilantro", "Cebolla morada", "Ají"],
        "resumenReceta": "Ceviche con algas chilenas y camarones; segmento Yo Invito replicado en clips verticales por uso de cochayuyo.",
        "senal": "medio-alto",
        "vistas": "Clips en alza",
        "engagement": "6.2%",
        "crecimiento": "+95%",
        "hashtags": ["#ceviche", "#cochayuyo", "#mariscos", "#recetachilena", "#foodtok", "#chile"],
        "plataformas": {
            "tiktok": "Clip del programa en TikTok",
            "instagram": "Reels de mariscos",
            "youtube": "Shorts del emplatado",
            "pinterest": "Pins ceviche chileno",
        },
    },
    {
        "slug": "espagueti-mariscos-merken",
        "fecha": "2026-06-16",
        "fuente": "https://www.biobiochile.cl/biobiotv/programas/yo-invito/2026/06/16/yo-invito-un-rico-espagueti-de-colores-con-mariscos-al-ajillo.shtml",
        "titulo": "Espagueti de colores con mariscos al ajillo",
        "formato": "Pasta · merkén y mar",
        "ingredientes": ["Pasta de colores", "Mariscos surtidos", "Ajo", "Vino blanco", "Merkén", "Aceite"],
        "resumenReceta": "Pasta con mariscos salteados y merkén; receta del chef Enrique Araya compartida en vertical por ingredientes locales.",
        "senal": "medio",
        "vistas": "Compartidos en Reels",
        "engagement": "5.8%",
        "crecimiento": "+88%",
        "hashtags": ["#espagueti", "#mariscos", "#merken", "#recetachilena", "#foodtok", "#pasta"],
        "plataformas": {
            "tiktok": "Salteado en TikTok",
            "instagram": "Reels de pasta",
            "youtube": "Shorts del ajillo",
            "pinterest": "Pasta con mariscos",
        },
    },
    {
        "slug": "cordero-miel-pastelera",
        "fecha": "2026-06-25",
        "fuente": "https://www.biobiochile.cl/biobiotv/programas/yo-invito/2026/06/25/yo-invito-cordero-a-la-miel-con-pastelera.shtml",
        "titulo": "Cordero a la miel con pastelera",
        "formato": "Asado · invierno",
        "ingredientes": ["Cordero", "Miel", "Ajo", "Vino tinto", "Cebolla", "Pastelera de choclo"],
        "resumenReceta": "Cordero macerado y glaseado con miel al horno; clip viral por técnica de dorado y acompañamiento pastelera.",
        "senal": "medio-alto",
        "vistas": "Clips invierno",
        "engagement": "6.0%",
        "crecimiento": "+102%",
        "hashtags": ["#cordero", "#miel", "#pastelera", "#recetachilena", "#foodtok", "#invierno"],
        "plataformas": {
            "tiktok": "Dorado del cordero TikTok",
            "instagram": "Reels de asado",
            "youtube": "Shorts del glaseado",
            "pinterest": "Cordero al horno",
        },
    },
    {
        "slug": "suprema-rellena-papas",
        "fecha": "2026-06-25",
        "fuente": "https://www.biobiochile.cl/biobiotv/programas/yo-invito/2026/06/25/yo-invito-una-suprema-de-ave-rellena-con-papas-gratinadas.shtml",
        "titulo": "Suprema de ave rellena con papas gratinadas",
        "formato": "Plato familiar · horneado",
        "ingredientes": ["Pechuga de pollo", "Jamón", "Queso", "Papas", "Crema", "Huevo"],
        "resumenReceta": "Pollo relleno con papas gratinadas; receta nostálgica del chef compartida en redes por lo rendidor del plato.",
        "senal": "medio",
        "vistas": "Guardados en Reels",
        "engagement": "5.9%",
        "crecimiento": "+90%",
        "hashtags": ["#suprema", "#pollo", "#papas", "#recetachilena", "#foodtok", "#horno"],
        "plataformas": {
            "tiktok": "Relleno en TikTok",
            "instagram": "Reels familiares",
            "youtube": "Shorts del gratinado",
            "pinterest": "Pollo relleno papas",
        },
    },
    {
        "slug": "recetario-caro-rocco-invierno",
        "fecha": "2026-06-26",
        "fuente": "https://reportediario.cl/2026/06/26/chef-caro-rocco-y-noni-lanzan-recetario-de-invierno-recetas-tradicionales-para-disfrutar-sin-culpa/",
        "titulo": "Recetario invierno Caro Rocco + Noni",
        "formato": "Campaña · dulces con alulosa",
        "ingredientes": ["Alulosa", "Manjar sin azúcar", "Harina", "Calabaza", "Huevos"],
        "resumenReceta": "Calzones rotos y picarones reinterpretados con Daily; clips de la chef y su abuela viralizados en Instagram.",
        "senal": "medio-alto",
        "vistas": "Campaña en Reels",
        "engagement": "6.3%",
        "crecimiento": "+115%",
        "hashtags": ["#carorocco", "#picarones", "#calzonesrotos", "#recetachilena", "#invierno", "#reels"],
        "plataformas": {
            "tiktok": "Clips de la campaña",
            "instagram": "Reels Caro + Noni",
            "youtube": "Shorts del recetario",
            "pinterest": "Dulces invierno Chile",
        },
    },
    {
        "slug": "churrascas-sarten",
        "fecha": "2026-06-27",
        "fuente": "https://www.encancha.cl/enlahora/bienestar/2026/06/27/receta-de-churrascas-chilenas-asi-de-facil-rapido-y-economico-puedes-preparar-este-pan-al-sarten/",
        "titulo": "Churrascas chilenas al sartén",
        "formato": "Pan rápido · sin leudar",
        "ingredientes": ["Harina sin polvos", "Mantequilla o aceite", "Sal", "Agua tibia", "Polvo de hornear"],
        "resumenReceta": "Pan chileno sin leudar en sartén; receta de Camila (Canal 13) replicada masivamente en TikTok por lo económico.",
        "senal": "alto",
        "vistas": "Alto share en Reels/TikTok",
        "engagement": "7.5%",
        "crecimiento": "+120%",
        "hashtags": ["#churrascas", "#panalsarten", "#recetachilena", "#comidacasera", "#foodtok", "#chile"],
        "plataformas": {
            "tiktok": "Ola churrascas TikTok",
            "instagram": "Reels al sartén",
            "youtube": "Shorts del dorado",
            "pinterest": "Pins churrascas caseras",
        },
    },
    {
        "slug": "carbonada-invierno",
        "fecha": "2025-05-18",
        "fuente": "https://www.encancha.cl/enlahora/bienestar/2025/05/18/receta-de-carbonada-chilena-este-plato-es-ideal-para-dias-de-bajas-temperaturas/",
        "titulo": "Carbonada chilena de invierno",
        "formato": "Sopa tradicional · verduras",
        "ingredientes": ["Posta rosada", "Papa", "Zapallo", "Choclo", "Porotos verdes", "Cebolla", "Ají de color"],
        "resumenReceta": "Caldo con carne y verduras de estación; receta replicada en TikTok cada ola de frío en la zona centro-sur.",
        "senal": "medio",
        "vistas": "Estacional en redes",
        "engagement": "5.5%",
        "crecimiento": "+75%",
        "hashtags": ["#carbonada", "#sopa", "#invierno", "#recetachilena", "#foodtok", "#caldo"],
        "plataformas": {
            "tiktok": "Carbonada en TikTok",
            "instagram": "Reels de invierno",
            "youtube": "Shorts del caldo",
            "pinterest": "Sopas chilenas",
        },
    },
    {
        "slug": "pebre-origen-debate",
        "fecha": "2026-01-07",
        "fuente": "https://www.biobiochile.cl/noticias/sociedad/debate/2026/01/07/origen-del-pebre-influencer-asegura-que-es-una-mezcla-de-chile-y-espana-y-redes-estallan.shtml",
        "titulo": "Debate del origen del pebre",
        "formato": "Viral · cocina tradicional",
        "ingredientes": ["Ají verde", "Cilantro", "Cebolla", "Aceite", "Vinagre", "Sal"],
        "resumenReceta": "Influencer español atribuye raíz catalana al pebre; estallido de comentarios y recetas caseras en TikTok chileno.",
        "senal": "medio-alto",
        "vistas": "Debate masivo",
        "engagement": "8.8%",
        "crecimiento": "+175%",
        "hashtags": ["#pebre", "#recetachilena", "#debate", "#foodtok", "#cilantro", "#chile"],
        "plataformas": {
            "tiktok": "Stitch del debate",
            "instagram": "Reels de pebre casero",
            "youtube": "Shorts de reacciones",
            "pinterest": "Recetas de pebre",
        },
    },
    {
        "slug": "pistacho-cultivo-chile",
        "fecha": "2025-07-01",
        "fuente": "https://www.sancarlosonline.cl/2025/07/fiebre-por-el-chocolate-de-dubai.html",
        "titulo": "Fiebre del pistacho (ingrediente Dubai)",
        "formato": "Ingrediente en alza · noticia",
        "ingredientes": ["Pistacho", "Pasta de pistacho", "Masa knafe", "Chocolate"],
        "resumenReceta": "Demanda por pistacho tras el viral del chocolate Dubai; noticia sobre cultivo y precio del ingrediente en Chile.",
        "senal": "medio",
        "vistas": "Búsquedas en alza",
        "engagement": "5.2%",
        "crecimiento": "+160%",
        "hashtags": ["#pistacho", "#chocolatedubai", "#ingredientes", "#foodnews", "#chile", "#knafe"],
        "plataformas": {
            "tiktok": "Ingredientes en TikTok",
            "instagram": "Reels informativos",
            "youtube": "Shorts explicativos",
            "pinterest": "Pins pistacho postres",
        },
    },
    {
        "slug": "chocolate-dubai-biobio",
        "fecha": "2025-03-21",
        "fuente": "https://www.biobiochile.cl/noticias/sociedad/viral/2025/03/21/que-es-el-chocolate-de-dubai-el-dulce-mas-extravagante-y-viral-del-momento-en-redes-sociales.shtml",
        "titulo": "Qué es el Chocolate de Dubai",
        "formato": "Explicativo · tendencia global",
        "ingredientes": ["Chocolate", "Pistacho", "Kunafa tostado", "Tahini", "Oro comestible"],
        "resumenReceta": "Noticia que introduce el dulce de FIX Dessert Chocolatier; pistacho y kunafa como combo viral en redes chilenas.",
        "senal": "muy-alto",
        "vistas": "120M+ ref. global",
        "engagement": "8.0%",
        "crecimiento": "+300%",
        "hashtags": ["#chocolatedubai", "#kunafa", "#pistacho", "#viral", "#foodtok", "#postre"],
        "plataformas": {
            "tiktok": "Explicación en TikTok",
            "instagram": "Reels del corte",
            "youtube": "Shorts del relleno",
            "pinterest": "Chocolate Dubai ideas",
        },
    },
]
